### PR TITLE
Font not ready yet for GF

### PR DESCRIPTION
**Pull request by emmamarichal**
Hello @meirsadan,

I'm Emma, I'm working on Frank Ruhl Libre update, in order to onboarding it on GF. Here are the modifications according the GF's specs:
- repo structure (readme, authors, contributors, ofl, etc.)
- set up the instances and config.yaml to export the font
- v-metrics uptaded
- some interpolation issues solved + Uogonek corrected.

I have some questions/remarks:
- Some glyphs were missing: I generated some automatically (pink in the source file), but some are still missing (in red). Do you think you can add them? It concerns 4 glyphs.
- Are the accent positions ok?
Capture d’écran 2022-10-14 à 11 31 49
Capture d’écran 2022-10-14 à 11 31 29

- Do you want a name for your ss01?
- I kept the old v-metrics (values on current font on Google Fonts), because they have to be the same
- You did well to rename the master medium "regular", because we need this master for the "variable font origin" parameter to work properly.
However, we need the values of the masters to be the same as the instances. Except that by putting "92" in the master regular, we got a regular instance that was too bold compared to the original. So I had to generate a regular master, and I kept the medium master so as not to alter the design.

Apart from that, everything is ok on my side, the font has no problem, thank you for this work!
You can merge this PR if you want to add the missing glyphs. If you can't, I can take care of it and add commits to this PR or make you a new one later.

Don't hesitate if you have any questions,
Thank you!

### CODE REVIEW

**Comment by emmamarichal** [comment]
Hello @meirsadan,
Have you seen this PR? Don't hesitate if you have any questions, I would be happy to help you on that project!
Cheers!

**Comment by meirsadan** [comment]
Hi @emmamarichal 
Thanks for pinging this, and for all your work. This is very helpful.
I have forwarded your revised Glyphs file and comments to Yanek of @fontef and he will review the changes. I'll update if there's anything we'll need more help with.
Can you please advise – once we make the changes and produce a newer Glyphs source file, is it preferable to merge your request, and then commit Yanek's newer source file? Or is it better to create a newer PR with all the approved changes?
Thanks so much

**Comment by emmamarichal** [comment]
Hello @meirsadan 
Ok thank you very much! 
It's better to merge my PR, then add your changes so I can pull them on my branch afterwards. Because otherwise we might have conflicts. After your changes, I'll just check that everything is ok and I'll do a PR again with the latest exports.
Thank you 😃

**Comment by fontef** [comment]
Thank you @emmamarichal!
We merged your pull request and updated the source file with our changes.
In addition to adding the missing glyphs, we also made some other small tweaks – such as labeling ss01, removing irrelevant legacy shapes, and updating our niqqud positioning code in the ccmp feature.
If this is okay, can you please regenerate the font files for us?
All the best

**Pull request merged**
